from dataclasses import dataclass, field
from decimal import Decimal

from source.constants import DECIMAL_ZERO


# Invoice class to hold all attributes of the invoice. This represents a single invoice generated by Fishbowl
# Note that Decimal types are used for all currency values to avoid floating point precision issues caused
# by the Fishbowl software. Every field has a default, so Invoice() default-constructs as before while callers
# may also supply any subset of fields up front, e.g. Invoice(customer_name="Alice", total=Decimal("385.00")).
@dataclass
class Invoice:

    # fmt:off
    customer_name: str          = ""                                 # Name of customer on invoice
    date: str                   = ""                                 # Date of invoice
    order_number: str           = ""                                 # Order Number, e.g. S12345
    po_number: str              = ""                                 # PO Number
    payment_terms: str          = ""                                 # Listed payment terms
    sales_rep: str              = ""                                 # Sales rep identifier
    labor_cost: Decimal         = DECIMAL_ZERO                       # Total cost of labor
    material_cost: Decimal      = DECIMAL_ZERO                       # Total cost of material
    shipping_cost: Decimal      = DECIMAL_ZERO                       # Total cost of shipping
    subtotal: Decimal           = DECIMAL_ZERO                       # subtotal, from summing labor_cost, material_cost, and shipping_cost
    sales_tax: Decimal          = DECIMAL_ZERO                       # Additional sales tax
    total: Decimal              = DECIMAL_ZERO                       # Calculated as subtotal plus sales_tax
    listed_total: Decimal       = DECIMAL_ZERO                       # Total as listed on the invoice, to compare to the calculated total
    page_contents: list[str]    = field(default_factory=list)        # List of strings, each string is the text from a page of the invoice PDF
    # fmt:on

    ###########################################################################
    ###                  Invoice -> to_formatted_string()                   ###
    ###########################################################################
    def to_formatted_string(self):
        """
        Returns a formatted string to output invoice contents

        Returns:
            str: A formatted string containing all of the invoice's fields on separate lines
        """

        return (
            "***********************************\n"
            "Processed Invoice Results:\n"
            f"Customer Name: {self.customer_name}\n"
            f"Invoice Date: {self.date}\n"
            f"Order Number: {self.order_number}\n"
            f"PO Number: {self.po_number}\n"
            f"Payment Terms: {self.payment_terms}\n"
            f"Sales Rep: {self.sales_rep}\n"
            f"Labor Cost: ${self.labor_cost}\n"
            f"Material Cost: ${self.material_cost}\n"
            f"Shipping Cost: ${self.shipping_cost}\n"
            f"Subtotal: ${self.subtotal}\n"
            f"Sales Tax: ${self.sales_tax}\n"
            f"Calculated Total: ${self.total}\n"
            f"Listed Total: ${self.listed_total}\n"
            "***********************************\n"
        )
